name: render_pdf

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: simonzimmer/resume

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Render pdf
        run: |
            docker build -t ${IMAGE_NAME} .
            docker run -v ${PWD}/:/latex/ ${IMAGE_NAME} bash -c "xelatex -interaction=nonstopmode -output-directory=/latex/docs resume_dev.tex"
            docker run -v ${PWD}/:/latex/ ${IMAGE_NAME} bash -c "xelatex -interaction=nonstopmode -output-directory=/latex/docs resume_art.tex"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
